name: build

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/download-artifact@v4
      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        with:
          command: upload
          args: --non-interactive --skip-existing wheels-*/*
